/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_projects__project_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Job */
        get: operations["get_import_job_api_v1_import_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Import */
        post: operations["retry_import_api_v1_import_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_task_packages_get"];
        put?: never;
        /** Create Package */
        post: operations["create_package_api_v1_task_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Package */
        post: operations["publish_package_api_v1_task_packages__package_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Package Groups */
        get: operations["list_package_groups_api_v1_task_packages__package_id__groups_get"];
        put?: never;
        /** Add Package Group */
        post: operations["add_package_group_api_v1_task_packages__package_id__groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/group-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Group Options */
        get: operations["list_group_options_api_v1_task_packages__package_id__group_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Package Group */
        delete: operations["remove_package_group_api_v1_task_packages__package_id__groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_task_packages__package_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/annotation-tasks/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Annotation */
        post: operations["claim_annotation_api_v1_annotation_tasks_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-tasks/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Review */
        post: operations["claim_review_api_v1_review_tasks_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/my-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Tasks */
        get: operations["my_tasks_api_v1_my_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-packages/{package_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Items */
        post: operations["assign_items_api_v1_task_packages__package_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-items/{item_id}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reclaim Item */
        post: operations["reclaim_item_api_v1_task_items__item_id__reclaim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_user_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_user_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_user_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Group */
        patch: operations["update_group_api_v1_user_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/user-groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_user_groups__group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-groups/{group_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_user_groups__group_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Work Context */
        get: operations["work_context_api_v1_work_items__item_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Draft */
        put: operations["save_draft_api_v1_work_items__item_id__draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Annotation */
        post: operations["submit_annotation_api_v1_work_items__item_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Item */
        post: operations["review_item_api_v1_work_items__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/review-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Review Draft */
        put: operations["save_review_draft_api_v1_work_items__item_id__review_draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Annotations */
        post: operations["clear_annotations_api_v1_work_items__item_id__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Data */
        get: operations["item_data_api_v1_work_items__item_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/media/{media_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Item Media */
        get: operations["item_media_api_v1_work_items__item_id__media__media_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quality Batches */
        get: operations["list_quality_batches_api_v1_quality_batches_get"];
        put?: never;
        /** Create Quality Batch */
        post: operations["create_quality_batch_api_v1_quality_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quality Batch */
        get: operations["get_quality_batch_api_v1_quality_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/quality-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality History */
        get: operations["quality_history_api_v1_work_items__item_id__quality_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{item_id}/quality-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quality Check */
        post: operations["quality_check_api_v1_work_items__item_id__quality_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quality-batches/{batch_id}/items/{item_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Quality Batch Item */
        post: operations["check_quality_batch_item_api_v1_quality_batches__batch_id__items__item_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Stats */
        get: operations["project_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/tasks.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Report */
        get: operations["task_report_api_v1_reports_tasks_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-statistics/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Work Statistics */
        get: operations["personal_work_statistics_api_v1_work_statistics_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-statistics/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People Work Statistics */
        get: operations["people_work_statistics_api_v1_work_statistics_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-statistics/me.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personal Work Csv */
        get: operations["personal_work_csv_api_v1_work_statistics_me_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-statistics/people.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People Work Csv */
        get: operations["people_work_csv_api_v1_work_statistics_people_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentRequest */
        AssignmentRequest: {
            /** Item Ids */
            item_ids: string[];
            /** Assignee Id */
            assignee_id: string;
            /** Stage */
            stage: string;
        };
        /**
         * ClaimPolicy
         * @enum {string}
         */
        ClaimPolicy: "sequential" | "random";
        /** DatasetCreate */
        DatasetCreate: {
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Root Path */
            root_path: string;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Root Path */
            root_path: string;
            status: components["schemas"]["DatasetStatus"];
            /** Episode Count */
            episode_count: number;
            /** Warning Count */
            warning_count: number;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DatasetStatus
         * @enum {string}
         */
        DatasetStatus: "pending" | "importing" | "ready" | "failed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportJobOut */
        ImportJobOut: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id: string;
            status: components["schemas"]["DatasetStatus"];
            /** Processed Count */
            processed_count: number;
            /** Warning Count */
            warning_count: number;
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Error Message */
            error_message: string | null;
        };
        /**
         * ItemStatus
         * @enum {string}
         */
        ItemStatus: "available" | "annotation_assigned" | "annotating" | "review_pending" | "review_assigned" | "reviewing" | "changes_requested" | "completed" | "cancelled";
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MemberCreate */
        MemberCreate: {
            /** User Id */
            user_id: string;
        };
        /** PackageCreate */
        PackageCreate: {
            /** Project Id */
            project_id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default sequential */
            claim_policy: components["schemas"]["ClaimPolicy"];
            /**
             * Item Count
             * @description 本次任务包创建的条目数量；新客户端应始终传入。
             */
            item_count?: number | null;
            /** Random Seed */
            random_seed?: number | null;
            /**
             * Episode Indices
             * @deprecated
             * @description 已废弃。旧客户端可继续使用，服务端会从其中排除已分配 episode。
             */
            episode_indices?: number[] | null;
            /**
             * Episode Start
             * @deprecated
             * @description 已废弃。新客户端请改用 item_count。
             */
            episode_start?: number | null;
            /**
             * Episode End
             * @deprecated
             * @description 已废弃。新客户端请改用 item_count。
             */
            episode_end?: number | null;
            /**
             * Member Ids
             * @deprecated
             * @description 已废弃。任务包权限由项目成员关系决定，此字段仅为兼容旧客户端保留。
             */
            member_ids?: string[] | null;
        };
        /** PackageOut */
        PackageOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["PackageStatus"];
            claim_policy: components["schemas"]["ClaimPolicy"];
            /** Random Seed */
            random_seed: number | null;
            /**
             * Group Access Configured
             * @default false
             */
            group_access_configured: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Total Items
             * @default 0
             */
            total_items: number;
            /**
             * Claimed Items
             * @default 0
             */
            claimed_items: number;
            /**
             * Annotated Items
             * @default 0
             */
            annotated_items: number;
            /**
             * Reviewed Items
             * @default 0
             */
            reviewed_items: number;
            /**
             * Authorized Groups
             * @default []
             */
            authorized_groups: components["schemas"]["UserGroupSummaryOut"][];
        };
        /**
         * PackageStatus
         * @enum {string}
         */
        PackageStatus: "draft" | "published" | "closed";
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PeopleWorkStatisticsOut */
        PeopleWorkStatisticsOut: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** People */
            people: components["schemas"]["WorkMetricOut"][];
        };
        /** PersonalWorkStatisticsOut */
        PersonalWorkStatisticsOut: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "day" | "week" | "month";
            summary: components["schemas"]["WorkMetricOut"];
            /** Periods */
            periods: components["schemas"]["WorkMetricOut"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * QaStatus
         * @enum {string}
         */
        QaStatus: "unchecked" | "passed" | "rejected";
        /** QualityBatchCreate */
        QualityBatchCreate: {
            /** Package Id */
            package_id: string;
            /** Assignee Id */
            assignee_id?: string | null;
            /**
             * Mode
             * @default ratio
             * @enum {string}
             */
            mode: "all" | "ratio" | "count";
            /**
             * Percent
             * @default 10
             */
            percent: number;
            /**
             * Count
             * @default 20
             */
            count: number;
            /**
             * Seed
             * @default quality
             */
            seed: string;
            /**
             * Only Unchecked
             * @default true
             */
            only_unchecked: boolean;
        };
        /** QualityBatchDetailOut */
        QualityBatchDetailOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Package Id */
            package_id: string;
            /** Created By Id */
            created_by_id: string;
            /** Assignee Id */
            assignee_id: string | null;
            /** Mode */
            mode: string;
            /** Sample Percent */
            sample_percent: number | null;
            /** Sample Count */
            sample_count: number | null;
            /** Seed */
            seed: string;
            /** Only Unchecked */
            only_unchecked: boolean;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Total Samples */
            total_samples: number;
            /** Checked Samples */
            checked_samples: number;
            /** Passed Samples */
            passed_samples: number;
            /** Rejected Samples */
            rejected_samples: number;
            /** Samples */
            samples: components["schemas"]["QualitySampleOut"][];
        };
        /** QualityBatchOut */
        QualityBatchOut: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Package Id */
            package_id: string;
            /** Created By Id */
            created_by_id: string;
            /** Assignee Id */
            assignee_id: string | null;
            /** Mode */
            mode: string;
            /** Sample Percent */
            sample_percent: number | null;
            /** Sample Count */
            sample_count: number | null;
            /** Seed */
            seed: string;
            /** Only Unchecked */
            only_unchecked: boolean;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Total Samples */
            total_samples: number;
            /** Checked Samples */
            checked_samples: number;
            /** Passed Samples */
            passed_samples: number;
            /** Rejected Samples */
            rejected_samples: number;
        };
        /** QualityCheckOut */
        QualityCheckOut: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string | null;
            /** Task Item Id */
            task_item_id: string;
            /** Reviewer Id */
            reviewer_id: string;
            result: components["schemas"]["QaStatus"];
            /** Comment */
            comment: string | null;
            /** Revision Id */
            revision_id: string | null;
            /** Revision Version */
            revision_version: number | null;
            /** Revision Hash */
            revision_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QualityInput */
        QualityInput: {
            result: components["schemas"]["QaStatus"];
            /** Comment */
            comment?: string | null;
            /** Batch Id */
            batch_id?: string | null;
        };
        /** QualitySampleOut */
        QualitySampleOut: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Task Item Id */
            task_item_id: string;
            /** Sample Order */
            sample_order: number;
            item: components["schemas"]["TaskItemOut"];
            latest_check?: components["schemas"]["QualityCheckOut"] | null;
        };
        /** ReclaimRequest */
        ReclaimRequest: {
            /** Reason */
            reason: string;
        };
        /** ReviewInput */
        ReviewInput: {
            /** Decision */
            decision: string;
            /** Comment */
            comment?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** RevisionInput */
        RevisionInput: {
            /**
             * Schema Version
             * @default segments.v1
             */
            schema_version: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Base Revision Id */
            base_revision_id?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "developer_admin" | "annotation_manager" | "outsourcing_manager" | "reviewer" | "annotator";
        /** StatsOut */
        StatsOut: {
            /** Project Id */
            project_id: string;
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Completion Rate */
            completion_rate: number;
            /** Effective Video Seconds */
            effective_video_seconds: number;
            /** By Person */
            by_person: {
                [key: string]: unknown;
            }[];
        };
        /** TaskItemOut */
        TaskItemOut: {
            /** Id */
            id: string;
            /** Package Id */
            package_id: string;
            /** Episode Id */
            episode_id: string;
            /** Claim Order */
            claim_order: number;
            status: components["schemas"]["ItemStatus"];
            /** Annotator Id */
            annotator_id: string | null;
            /** Reviewer Id */
            reviewer_id: string | null;
            qa_status: components["schemas"]["QaStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskPackageGroupCreate */
        TaskPackageGroupCreate: {
            /** Group Id */
            group_id: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            role: components["schemas"]["Role"];
            /**
             * Project Ids
             * @default []
             */
            project_ids: string[];
            /**
             * Group Ids
             * @default []
             */
            group_ids: string[];
        };
        /** UserGroupCreate */
        UserGroupCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Manager Id */
            manager_id?: string | null;
        };
        /** UserGroupMemberCreate */
        UserGroupMemberCreate: {
            /** User Id */
            user_id: string;
        };
        /** UserGroupMemberOut */
        UserGroupMemberOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
        };
        /** UserGroupOut */
        UserGroupOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created By Id */
            created_by_id: string;
            /** Manager Id */
            manager_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Member Count */
            member_count: number;
            /** Members */
            members: components["schemas"]["UserGroupMemberOut"][];
        };
        /** UserGroupSummaryOut */
        UserGroupSummaryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Member Count */
            member_count: number;
        };
        /** UserGroupUpdate */
        UserGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Manager Id */
            manager_id?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Reset Password */
            reset_password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkContext */
        WorkContext: {
            item: components["schemas"]["TaskItemOut"];
            annotator?: components["schemas"]["WorkContextUser"] | null;
            reviewer?: components["schemas"]["WorkContextUser"] | null;
            /** Episode Index */
            episode_index: number;
            /** Length */
            length: number;
            /** Fps */
            fps: number;
            /** Tasks */
            tasks: string[];
            /** Data Url */
            data_url: string;
            /** Video Urls */
            video_urls: {
                [key: string]: string;
            };
            /** Preview Speed Factor */
            preview_speed_factor: number;
            /** Latest Revision */
            latest_revision: {
                [key: string]: unknown;
            } | null;
            /** Review Comment */
            review_comment?: string | null;
            /** Quality Comment */
            quality_comment?: string | null;
        };
        /** WorkContextUser */
        WorkContextUser: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
        };
        /** WorkMetricOut */
        WorkMetricOut: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Claimed Count */
            claimed_count: number;
            /** First Submissions */
            first_submissions: number;
            /** Resubmissions */
            resubmissions: number;
            /** Returned Count */
            returned_count: number;
            /** Final Approved Count */
            final_approved_count: number;
            /** Effective Video Seconds */
            effective_video_seconds: number;
            /** Average Completion Seconds */
            average_completion_seconds: number | null;
            /** First Pass Rate */
            first_pass_rate: number;
            /** Rework Rate */
            rework_rate: number;
            /** Review Claimed Count */
            review_claimed_count: number;
            /** Review Count */
            review_count: number;
            /** Approved Count */
            approved_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Review Pass Rate */
            review_pass_rate: number;
            /** Review Return Rate */
            review_return_rate: number;
            /** Average Review Seconds */
            average_review_seconds: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_projects__project_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_job_api_v1_import_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_import_api_v1_import_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_v1_task_packages_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_api_v1_task_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_package_api_v1_task_packages__package_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_package_groups_api_v1_task_packages__package_id__groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_package_group_api_v1_task_packages__package_id__groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPackageGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_group_options_api_v1_task_packages__package_id__group_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_package_group_api_v1_task_packages__package_id__groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                group_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_task_packages__package_id__items_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ItemStatus"] | null;
            };
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_annotation_api_v1_annotation_tasks_claim_post: {
        parameters: {
            query: {
                package_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_review_api_v1_review_tasks_claim_post: {
        parameters: {
            query: {
                package_id: string;
                claim_policy?: components["schemas"]["ClaimPolicy"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_tasks_api_v1_my_tasks_get: {
        parameters: {
            query?: {
                stage?: string;
                view?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_items_api_v1_task_packages__package_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reclaim_item_api_v1_task_items__item_id__reclaim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReclaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_api_v1_user_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_user_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_user_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_v1_user_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_user_groups__group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroupMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_user_groups__group_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                user_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    work_context_api_v1_work_items__item_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_api_v1_work_items__item_id__draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_annotation_api_v1_work_items__item_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_item_api_v1_work_items__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_review_draft_api_v1_work_items__item_id__review_draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_annotations_api_v1_work_items__item_id__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_data_api_v1_work_items__item_id__data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_media_api_v1_work_items__item_id__media__media_key__get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
                "If-None-Match"?: string | null;
                "If-Modified-Since"?: string | null;
            };
            path: {
                item_id: string;
                media_key: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Partial video content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Video has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requested byte range cannot be satisfied */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quality_batches_api_v1_quality_batches_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                package_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityBatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quality_batch_api_v1_quality_batches_post: {
        parameters: {
            query?: {
                include_samples?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityBatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityBatchDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_batch_api_v1_quality_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityBatchDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_history_api_v1_work_items__item_id__quality_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityCheckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quality_check_api_v1_work_items__item_id__quality_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_quality_batch_item_api_v1_quality_batches__batch_id__items__item_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
                item_id: string;
            };
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_stats_api_v1_stats_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_report_api_v1_reports_tasks_csv_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personal_work_statistics_api_v1_work_statistics_me_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalWorkStatisticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_work_statistics_api_v1_work_statistics_people_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                role?: components["schemas"]["Role"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleWorkStatisticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personal_work_csv_api_v1_work_statistics_me_csv_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_work_csv_api_v1_work_statistics_people_csv_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                role?: components["schemas"]["Role"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                annotate_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
