export const queryKeys = {
  me: ["me"] as const,
  projects: ["projects"] as const,
  users: ["users"] as const,
  datasetsRoot: ["datasets"] as const,
  datasets: (projectId?: string) => ["datasets", projectId] as const,
  packages: (projectId?: string) => ["packages", projectId] as const,
  packageItems: (packageId: string) => ["package-items", packageId] as const,
  myTasks: (review: boolean) => ["my-tasks", review] as const,
  statsEmpty: ["stats", "empty"] as const,
  stats: (projectId: string) => ["stats", projectId] as const,
  qualityItemsEmpty: ["quality-items", "empty"] as const,
  qualityItemsRoot: ["quality-items"] as const,
  qualityItems: (packageId: string) => ["quality-items", packageId] as const,
  workContext: (itemId: string) => ["work-context", itemId] as const,
};
