export const queryKeys = {
  me: ["me"] as const,
  projects: ["projects"] as const,
  users: ["users"] as const,
  userGroups: ["user-groups"] as const,
  datasetsRoot: ["datasets"] as const,
  datasets: (projectId?: string) => ["datasets", projectId] as const,
  packages: (projectId?: string) => ["packages", projectId] as const,
  packageGroups: (packageId: string) => ["package-groups", packageId] as const,
  packageGroupOptions: (packageId: string) => ["package-group-options", packageId] as const,
  packageItems: (packageId: string) => ["package-items", packageId] as const,
  myTasksRoot: (review: boolean) => ["my-tasks", review] as const,
  myTasks: (review: boolean, view: "pending" | "history" = "pending") =>
    ["my-tasks", review, view] as const,
  statsEmpty: ["stats", "empty"] as const,
  stats: (projectId: string) => ["stats", projectId] as const,
  personalWork: (
    projectId: string | undefined,
    startDate: string,
    endDate: string,
    granularity: string,
  ) => ["personal-work", projectId, startDate, endDate, granularity] as const,
  peopleWork: (
    projectId: string | undefined,
    startDate: string,
    endDate: string,
    role: string | undefined,
  ) => ["people-work", projectId, startDate, endDate, role] as const,
  qualityItemsEmpty: ["quality-items", "empty"] as const,
  qualityItemsRoot: ["quality-items"] as const,
  qualityItems: (packageId: string) => ["quality-items", packageId] as const,
  qualityBatches: (projectId?: string) => ["quality-batches", projectId] as const,
  qualityBatch: (batchId: string) => ["quality-batch", batchId] as const,
  qualityHistory: (itemId: string) => ["quality-history", itemId] as const,
  workContext: (itemId: string) => ["work-context", itemId] as const,
};
